server:
  port: 8080
  
  spring:
  datasource:
    # MariaDB
    data-username: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/northwind
    username: root
    password: ****
    connectionProperties: useUnicode=true&characterEncoding=UTF-8&serverTimezone=JST


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # MariaDB
        dialect: org.hibernate.dialect.MariaDBDialect
