
server:
  port: 8080
  
spring:
  datasource:
    data-username: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/northdb
    username: root
    password: ****
    connectionProperties: useUnicode=true&characterEncoding=UTF-8&serverTimezone=JST

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    root: warn
    com.example.demo: warn
  file: logs/dev.log
  

